Updated Jenkinsfile

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -43,10 +43,28 @@ pipeline {
             }
         }
 
+        stage('Install kubectl') {
+            steps {
+                script {
+                    sh """
+                    if ! command -v kubectl &> /dev/null
+                    then
+                        echo 'kubectl not found, installing...'
+                        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+                        chmod +x kubectl
+                        sudo mv kubectl /usr/local/bin/
+                    else
+                        echo 'kubectl is already installed'
+                    fi
+                    """
+                }
+            }
+        }
+
         stage('Deploy to Kubernetes') {
             steps {
                 script {
-                    sh "kubectl apply -f ~/workspace/Quiz-App/k8s/"
+                    sh "kubectl apply -f /var/lib/jenkins/workspace/Quiz-App/k8s/"
                 }
             }
         }
@@ -61,4 +79,3 @@ pipeline {
         }
     }
 }
-
